---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: prowlarr_latest
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: prowlarr_develop
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: prowlarr_nightly
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      prowlarr_latest:
        ansible_user: podman
        prowlarr_version: latest
      prowlarr_develop:
        ansible_user: podman
        prowlarr_version: latest
      prowlarr_nightly:
        ansible_user: podman
        prowlarr_version: latest
verifier:
  name: ansible
